### ISSUE TITLE
Wrong deployment type shown in FEV

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNServices2#121]
Todd found the wrong deployment type on a sensor in FEV. I Suspect the issue comes from the services. On this Endpoint, the site comes back with the wrong deployment type - (find the site PRNAR23505 in response - StatusID 4 = proposed)
https://stn.wim.usgs.gov/STNServices/Instruments/FilteredInstruments.json?Event=182&EventType=&EventStatus=&States=&County=&CurrentStatus=&CollectionCondition=&SensorType=&DeploymentType=

Todd's findings below:
>I just ran across another strangeness in FEV.  Site number PRNAR23505 for the Irma event shows a status of "Proposed" in FEV, but it is clearly "Retrieved" in STN:
![image](https://user-images.githubusercontent.com/12058013/32255751-053d28f8-be81-11e7-8b71-d9b4f8a7d0d1.png)

![image](https://user-images.githubusercontent.com/12058013/32255746-f8daf630-be80-11e7-8473-2dd8befa5a7a.png)

**Comment by troddick** [comment]
Fixed functionality of proposing new sensors in stnweb ( occasionally an existing sensor was getting grabbed instead of creating a new one and then a new status of proposed was getting added to it).
Need to search the db for any other sensor statuses with a proposed state after its deployed/retrieved state dates.

**Comment by troddick** [comment]
This particular case has been fixed. There is still an underlying flaw in the design of posting new sensors when a sensor with matching properties already exist in the db.
