### ISSUE TITLE
Discard STNWebTest EC2 instance

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNServices2#145]
We will be be using the new EC2 instance for STN Test created with this ticket: https://github.com/USGS-WiM/STNServices2/issues/144

Leave the stntest RDS as is. We will be using it with refactored services.

**Comment by lprivette** [comment]
When an EC2 instance is discarded we have the option to save a backup, right? There appear to be many artifacts of STN/FEV on this server that are before my time so I'd like to have a backup of it just in case

**Comment by aaronstephenson** [comment]
Yes. We can make a backup at any time, not just at the time of termination. We could either create an AMI (easiest) or take snapshots of the EBS volumes (more time consuming in the event of a restore because you would have to launch a new EC2 instance with the exact same OS version, then swap out the volumes).

**Comment by lprivette** [comment]
Since this is a test environment I'm not worried about needing to rush to restore. So a snapshot of the EBS volumes would be fine. If there's no big price or time difference, then maybe just do the method that works best for your/Dan's time.

**Comment by aaronstephenson** [comment]
Backed up and now terminated.
